# Pre-commit configuration for MCP Azure DevOps Server
# Senior Software Architect approach: balanced quality vs pragmatism
repos:
  # Python code formatting with black
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=100"]

  # Import sorting with isort
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length=100"]

  # Python linting with flake8 (pragmatic configuration)
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=100"
          - "--extend-ignore=E203,W503,F401,E402,C901,F541,F841"
          - "--max-complexity=15"
        exclude: ^(test_.*\.py|.*_test\.py|debug_.*\.py|setup_dev\.py)$

  # Security scanning with bandit (exclude dev/test scripts)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        exclude: ^(test_.*\.py|.*_test\.py|debug_.*\.py|setup_dev\.py)$

  # Generic code quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Basic file checks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']

      # Python-specific checks (core only)
      - id: check-ast
      - id: debug-statements
      - id: name-tests-test
        args: ['--pytest-test-first']

      # Git and merge conflict detection
      - id: check-merge-conflict
      - id: check-case-conflict

# Configuration for CI/CD integration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
